/*
Copyright © 2024 Wind River Systems, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

import (
	"github.com/spf13/cobra"
)

const (
	userSetExample = `  {{.appName}} user set -t"User token"   set user token`
)

var setTokenCmd = &cobra.Command{
	Use:              "set",
	Aliases:          []string{"s"},
	Short:            "Set the current user token",
	Long:             `Set the current user token. The user token is generated by Wind River Studio Security Scanner. The user needs to open https://studio.windriver.com/scan/ and login, open the user profile page, then apply to generate the user token and copy it.`,
	Example:          formatExample(userSetExample),
	TraverseChildren: true,
	Run: func(cmd *cobra.Command, args []string) {
		executeUserSubCommand("set")
	},
}

func init() {
	setTokenCmd.Flags().StringVarP(&USER_TOKEN, "userToken", "t", "", "User Token")
	setTokenCmd.MarkFlagRequired("userToken")
	userCmd.AddCommand(setTokenCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// projectCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// projectCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")

	//projectCmd.Flags().BoolP("projectID", "id", false, "project ID")
}
